### ISSUE TITLE
thanks for these docker images... so here is another one

### ISSUE THREAD

**Issue by dreamcat4** [jessfraz/dockerfiles#124]
Hi,
As a 'thank you' for providing certain dockerized apps, like firefox etc. Here is to share with you my newest creation:

[IRC Ultimate Everything Docker image](https://github.com/dreamcat4/docker-images/tree/master/irc)

**Comment by jfrazelle** [comment]
Ah that's so cool!

On Monday, April 11, 2016, Dreamcat4 <notifications@github.com> wrote:

> Hi,
> As a 'thank you' for providing certain dockerized apps, like firefox etc.
> Here is to share with you my newest creation:
>
> Announcing my IRC Ultimate Everything Docker image
> <https://github.com/dreamcat4/docker-images/tree/master/irc>
>
> *And enjoy the heady excesses*. Or not, as you wish. Perhaps it is too
> much for some. But since this image contains so many useful bits and
> pieces. Can copy from / take / pillage for whichever specific parts. From
> irssi to znc to more. It's all in there.*
>
> In fact the Dockerfile is already orderded into self-contained sections
> for each IRC sevice(s). To be broken up / separate out. Well either way or
> whatever you like.
>
> I just use it as it is, being my own docker image. Well, with a layered
> and pre-seeded default config. Not to pollute or hamper with other people's
> own individual customizations. We certainly wouldn't want that.
>
> *1.4GB Image size.
>
> *Just thought it would be something cool or different to look at.*
> G'day.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/124>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jessfraz** [comment]
closing as this is not bugs with this repo, thanks! but feel free to discuss!
