### ISSUE TITLE
Docker & Chrome

### ISSUE THREAD

**Issue by senrabdet** [jessfraz/dockerfiles#156]
Hi Jess:

How are you?  I don't know if you're still looking at new issues but am stumped so figured I'd try.  I'm trying to get Chrome to run in Docker per https://github.com/jfrazelle/dockerfiles/blob/master/chrome/stable/Dockerfile.  My sense is Google has changed how it does sandboxing (and I can get chrome to start with the no sandbox flag).

Per some other posts (https://blog.docker.com/2016/02/docker-engine-1-10-security/, https://github.com/jfrazelle/dockerfiles/issues/17 and https://github.com/jfrazelle/dockerfiles/issues/65#) I believe I need to turn on user namespaces in my kernel (Debian Stretch kernel 4.6.0-1, Docker 1.11.2). 

Q1:  am I on the right track?  It's been a long time since I've added re-compiled a kernel and am hoping to avoid this.

Q:  do you know of anyone who has gotten chrome working that might have some scripts I could use to upgrade the kernel?

Thanks....and best wishes.

**Comment by jfrazelle** [comment]
Hey there's a bunch of issues about this, a lot has to do with userns being
enabled in your kernel. Look at a few of the closed issues here they might
be able to help

On Tuesday, June 28, 2016, senrabdet <notifications@github.com> wrote:

> Hi Jess:
>
> How are you? I don't know if you're still looking at new issues but am
> stumped so figured I'd try. I'm trying to get Chrome to run in Docker per
> https://github.com/jfrazelle/dockerfiles/blob/master/chrome/stable/Dockerfile.
> My sense is Google has changed how it does sandboxing (and I can get chrome
> to start with the no sandbox flag).
>
> Per some other posts (
> https://blog.docker.com/2016/02/docker-engine-1-10-security/, #17
> <https://github.com/jfrazelle/dockerfiles/issues/17> and #65
> <https://github.com/jfrazelle/dockerfiles/issues/65>) I believe I need to
> turn on user namespaces in my kernel (Debian Stretch kernel 4.6.0-1, Docker
> 1.11.2).
>
> Q1: am I on the right track? It's been a long time since I've added
> re-compiled a kernel and am hoping to avoid this.
>
> Q: do you know of anyone who has gotten chrome working that might have
> some scripts I could use to upgrade the kernel?
>
> Thanks....and best wishes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/156>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbFKNYllezAsLiboZKrcg8lPnDwTsks5qQUiEgaJpZM4JARl->
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
Thanks Jess....have looked at #17, #65 and a few others but am stuck (am not getting traction either on how to modify kernel).  Will keep at it..great to know you're still monitoring!!! Great admiration:)

**Comment by senrabdet** [comment]
Hi Jess (All):

One more...I think in version of my kernel (Debian Stretch kernel 4.6.0-1, Docker 1.11.2) that user namespaces are enabled by default, so I'm not getting the "Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted" error.  

Instead, I'm getting:
docker: Error response from daemon: Container command 'google-chrome' could not be invoked..

from:
docker run -it --cpuset-cpus 0 --memory 512mb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data --device /dev/snd --name chrome jess/chrome

or 
docker run -d \
>         --memory 3gb \
>         -v /etc/localtime:/etc/localtime:ro \
>         -v /tmp/.X11-unix:/tmp/.X11-unix \
>         -e DISPLAY=unix$DISPLAY \
>         -v $HOME/Downloads:/root/Downloads \
>         -v $HOME/Pictures:/root/Pictures \
>         -v $HOME/Torrents:/root/Torrents \
>         -v $HOME/.chrome:/data \
>         -v /dev/shm:/dev/shm \
>         -v /etc/hosts:/etc/hosts \
>         --device /dev/snd \
>         --device /dev/dri \
>         --group-add audio \
>         --group-add video \
>         --name chrome \
>         jess/chrome --user-data-dir=/data --force-device-scale-factor=1 \
>         --proxy-server="$proxy" --host-resolver-rules="$map" "$args"

The container is created and I think Chrome tries to start...

...which stumps me because "google-chrome" works if I install it in directly in another VM (i.e., not in docker; it's not installed in my virtualbox instance where I'm working on getting docker & chrome to work).  The "hello world" test works (docker run -it ubuntu /bin/echo 'Hello "World') as does Jess' iceweasel (docker run -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -e DISPLAY=unix$DISPLAY jess/iceweasel) so I think my overall setup is working. 

Has Google changed (again) something so I need to change my docker file?  Will keep at it, but any thoughts?

**Comment by jfrazelle** [comment]
You need custom second profile or to run with --seccomp unconfined, there's
a custom profile in my dotfiles repo

On Wednesday, June 29, 2016, senrabdet <notifications@github.com> wrote:

> Hi Jess (All):
>
> One more...I think in version of my kernel (Debian Stretch kernel 4.6.0-1,
> Docker 1.11.2) that user namespaces are enabled by default, so I'm not
> getting the "Failed to move to new namespace: PID namespaces supported,
> Network namespace supported, but failed: errno = Operation not permitted"
> error.
>
> Instead, I'm getting:
> docker: Error response from daemon: Container command 'google-chrome'
> could not be invoked..
>
> from:
> docker run -it --cpuset-cpus 0 --memory 512mb -v
> /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v
> $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data
> --device /dev/snd --name chrome jess/chrome
>
> or
> docker run -d \
>
>     --memory 3gb \
>     -v /etc/localtime:/etc/localtime:ro \
>     -v /tmp/.X11-unix:/tmp/.X11-unix \
>     -e DISPLAY=unix$DISPLAY \
>     -v $HOME/Downloads:/root/Downloads \
>     -v $HOME/Pictures:/root/Pictures \
>     -v $HOME/Torrents:/root/Torrents \
>     -v $HOME/.chrome:/data \
>     -v /dev/shm:/dev/shm \
>     -v /etc/hosts:/etc/hosts \
>     --device /dev/snd \
>     --device /dev/dri \
>     --group-add audio \
>     --group-add video \
>     --name chrome \
>     jess/chrome --user-data-dir=/data --force-device-scale-factor=1 \
>     --proxy-server="$proxy" --host-resolver-rules="$map" "$args"
>
> The container is created and I think Chrome tries to start...
>
> ...which stumps me because "google-chrome" works if I install it in
> directly in another VM (i.e., not in docker; it's not installed in my
> virtualbox instance where I'm working on getting docker & chrome to work).
> The "hello world" test works (docker run -it ubuntu /bin/echo 'Hello
> "World') as does Jess' iceweasel (docker run -v
> /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -e DISPLAY=unix$DISPLAY
> jess/iceweasel) so I think my overall setup is working.
>
> Has Google changed (again) something so I need to change my docker file?
> Will keep at it, but any thoughts?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/156#issuecomment-229370436>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbG5dTOORXHY4xv-N893s1SNK24A_ks5qQn7-gaJpZM4JARl->
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
Thanks!  Will try second customer profile from your .files....You're the best..:)

**Comment by mosajjal** [comment]
After enabling user namespaces in the kernel (change the kernel config, enable it and then re-compile), I got it working by issuing:

`docker run -it --net host -v /etc/localtime:/etc/localtime:ro --cap-add SYS_ADMIN  --cpuset-cpus 0-5 --memory 2048mb  -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data -v /dev/snd:/dev/snd --privileged -v /dev/shm:/dev/shm  --name chrome --security-opt seccomp:/home/mosajjal/Desktop/chrome/chrome.json 82c09c90d3cc google-chrome --user-data-dir`

also, this is my chrome.json file:

http://termbin.com/3c94


it's worth mentioning if you have swap disabled in your computer, it'll crash multiple times. Be sure to enable swap in your host.

**Comment by senrabdet** [comment]
Thanks mosajjal!  Will give it a try, report back.  Q:  does --cap-add SYS_ADMIN pose security worries? Is the "82c09c90d3cc " command refer to a container?  Appreciate the help....am doing a number of tests, and will report back on your suggestion and tests later today.  Thanks!

**Comment by mosajjal** [comment]
sorry, replace 82c09c90d3cc with your image_id created by "docker build".

about the SYS_ADMIN.. well, you're already running chrome as root. So I don't see how can SYS_ADMIN can be worst. here's a good article about it though, take a look: 

https://lwn.net/Articles/486306/

**Comment by senrabdet** [comment]
Again, thanks:)  Will do some tests...report results.  Appreciate the help.

**Comment by senrabdet** [comment]
Hi again:

I have run some tests, no joy yet, but again appreciate all the help and very much want to get this working.   It's probably something dumb/obvious (including a pbuak) but beyond me.  Suspect it's in my kernel but am unsure how to tell (am running Debian Stretch kernel 4.6.0-1, Docker 1.11.2) and various indications (started to update recompile kernel, feedback from docker messages) that user namespaces are active in my kernel.

Tried mosajjal's and Jess' suggestions (I hope correctly) and get "docker: Error response from daemon: Container command 'google-chrome' could not be invoked.."

FYI at some point am hoping to run the chrome container where it is set to become another user (non root, as I can do in my other containers), but don't know if that's possible and figure that's secondary.

At this risk of "over sharing"...., am including various detail that I hope helps:

1)  Dockerfile

FROM debian:sid
MAINTAINER Jessica Frazelle <jess@docker.com>

ADD https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb /src/google-talkplugin_current_amd64.deb

# Install Chrome
RUN echo 'deb http://httpredir.debian.org/debian testing main' >> /etc/apt/sources.list && \
	apt-get update && apt-get install -y \
	ca-certificates \
	curl \
	hicolor-icon-theme \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libv4l-0 \
	-t testing \
	fonts-symbola \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	--no-install-recommends \
	&& dpkg -i '/src/google-talkplugin_current_amd64.deb' \
	&& apt-get purge --auto-remove -y curl \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /src/*.deb

COPY local.conf /etc/fonts/local.conf

ENTRYPOINT [ "google-chrome" ]
CMD [ "--user-data-dir=/data" ]

*  Have tried a couple different versions of this including one from issue 65 with

2)  Docker run command (net host and privledged rejected if running user namespaces, so excluded them from command):

docker run -it --name chrome -v /etc/localtime:/etc/localtime:ro --cap-add SYS_ADMIN --cpuset-cpus 0 --memory 2048mb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data -v /dev/snd:/dev/snd -v /dev/shm:/dev/shm --name chrome --security-opt seccomp=/home/user/Documents/Chrome/Jess1/a.json jess/chrome google-chrome --user-data-dir

I get the same result if I run  --security-opt seccomp=unconfined

3)  a.jason (is one provided by mosajjal -- also tried ones found on https://github.com/docker/docker/blob/master/profiles/seccomp/default.json and Jess' at https://github.com/jfrazelle/dotfiles/blob/master/etc/docker/seccomp/chrome.json with the same outcome.

4)  Docker Inspect (have added as attachment)
[DockerInspect.txt](https://github.com/jfrazelle/dockerfiles/files/341881/DockerInspect.txt)

5)  Systemctl status docker (errors may mean something, but I think they are because I wasn't using --rm)

 systemctl status docker
? docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-06-30 08:33:21 EDT; 3h 37min ago
     Docs: https://docs.docker.com
 Main PID: 770 (docker)
    Tasks: 20
   Memory: 61.9M
      CPU: 1min 23.649s
   CGroup: /system.slice/docker.service
           +-770 /usr/bin/docker daemon -H fd:// --userns-remap default
           +-864 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --start-timeout 2m

Jun 30 11:53:39 debian docker[770]: time="2016-06-30T11:53:39-04:00" level=error msg="containerd: start container" error="oci runtime error: could not synchroni
Jun 30 11:53:40 debian docker[770]: time="2016-06-30T11:53:40.020387411-04:00" level=error msg="Handler for POST /v1.23/containers/7df7a3e8ac6e7d275a56a442c8f13
Jun 30 11:54:31 debian docker[770]: time="2016-06-30T11:54:31.514335968-04:00" level=error msg="Handler for POST /v1.23/containers/create returned error: Confli
Jun 30 11:54:37 debian docker[770]: time="2016-06-30T11:54:37-04:00" level=error msg="containerd: start container" error="oci runtime error: could not synchroni
Jun 30 11:54:37 debian docker[770]: time="2016-06-30T11:54:37.988198554-04:00" level=error msg="Handler for POST /v1.23/containers/399eab5c18c1e30d7e0b021cb1a6d
Jun 30 12:05:40 debian docker[770]: time="2016-06-30T12:05:40.046395366-04:00" level=error msg="Handler for POST /v1.23/containers/create returned error: Confli
Jun 30 12:05:58 debian docker[770]: time="2016-06-30T12:05:58.819988891-04:00" level=error msg="Handler for GET /v1.23/containers/chrome/json returned error: No
Jun 30 12:05:58 debian docker[770]: time="2016-06-30T12:05:58.820769533-04:00" level=error msg="Handler for GET /v1.23/images/chrome/json returned error: No suc
Jun 30 12:06:06 debian docker[770]: time="2016-06-30T12:06:06-04:00" level=error msg="containerd: start container" error="oci runtime error: could not synchroni
Jun 30 12:06:06 debian docker[770]: time="2016-06-30T12:06:06.732255705-04:00" level=error msg="Handler for POST /v1.23/containers/f05e6b18b8c6322582e43eb76dece
lines 1-22/22 (END)

6)  Steps used to add --userns-remap to daemon
cp /lib/systemd/system/docker.service /etc/systemd/system/
nano /etc/systemd/system/docker.service
Change:  
ExecStart=/usr/bin/docker daemon --userns-remap=default -H fd://
systemctl daemon-reload
systemctl restart docker

7)  I believe my swap is functioning (gparted shows swap partition and) by:
cat /proc/meminfo
MemTotal:        1278664 kB
MemFree:           82872 kB
MemAvailable:     579576 kB
Buffers:           71696 kB
Cached:           535700 kB
SwapCached:        42396 kB
Active:           533680 kB
Inactive:         551536 kB
Active(anon):     218592 kB
Inactive(anon):   263712 kB
Active(file):     315088 kB
Inactive(file):   287824 kB
Unevictable:          32 kB
Mlocked:              32 kB
SwapTotal:       1307644 kB
SwapFree:        1066908 kB
Dirty:                32 kB
Writeback:             0 kB
AnonPages:        462984 kB
Mapped:           106760 kB
Shmem:              4612 kB
Slab:              65992 kB
SReclaimable:      45060 kB
SUnreclaim:        20932 kB
KernelStack:        4992 kB
PageTables:        17888 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1946976 kB
Committed_AS:    2691100 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       71616 kB
DirectMap2M:     1239040 kB

**Comment by jfrazelle** [comment]
You are running the docker daemon w userns? That won't work with chrome
because it needs special devices you can do it with more control in runc I
wrote a blog post on it

On Thursday, June 30, 2016, senrabdet <notifications@github.com> wrote:

> Hi again:
>
> I have run some tests, no joy yet, but again appreciate all the help and
> very much want to get this working. It's probably something dumb/obvious
> (including a pbuak) but beyond me. Suspect it's in my kernel but am unsure
> how to tell (am running Debian Stretch kernel 4.6.0-1, Docker 1.11.2) and
> various indications (started to update recompile kernel, feedback from
> docker messages) that user namespaces are active in my kernel.
>
> Tried mosajjal's and Jess' suggestions (I hope correctly) and get "docker:
> Error response from daemon: Container command 'google-chrome' could not be
> invoked.."
>
> FYI at some point am hoping to run the chrome container where it is set to
> become another user (non root, as I can do in my other containers), but
> don't know if that's possible and figure that's secondary.
>
> At this risk of "over sharing"...., am including various detail that I
> hope helps:
>
> 1) Dockerfile
>
> FROM debian:sid
> MAINTAINER Jessica Frazelle jess@docker.com
> <javascript:_e(%7B%7D,'cvml','jess@docker.com');>
>
> ADD https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
> /src/google-talkplugin_current_amd64.deb
> Install Chrome
>
> RUN echo 'deb http://httpredir.debian.org/debian testing main' >>
> /etc/apt/sources.list && \
> apt-get update && apt-get install -y \
> ca-certificates \
> curl \
> hicolor-icon-theme \
> libgl1-mesa-dri \
> libgl1-mesa-glx \
> libv4l-0 \
> -t testing \
> fonts-symbola \
> --no-install-recommends \
> && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key
> add - \
> && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
> main" > /etc/apt/sources.list.d/google.list \
> && apt-get update && apt-get install -y \
> google-chrome-stable \
> --no-install-recommends \
> && dpkg -i '/src/google-talkplugin_current_amd64.deb' \
> && apt-get purge --auto-remove -y curl \
> && rm -rf /var/lib/apt/lists/* \
> && rm -rf /src/*.deb
>
> COPY local.conf /etc/fonts/local.conf
>
> ENTRYPOINT [ "google-chrome" ]
> CMD [ "--user-data-dir=/data" ]
>
>    - Have tried a couple different versions of this including one from
>    issue 65 with
>
> 2) Docker run command (net host and privledged rejected if running user
> namespaces, so excluded them from command):
>
> docker run -it --name chrome -v /etc/localtime:/etc/localtime:ro --cap-add
> SYS_ADMIN --cpuset-cpus 0 --memory 2048mb -v /tmp/.X11-unix:/tmp/.X11-unix
> -e DISPLAY=unix$DISPLAY -v $HOME/Downloads:/root/Downloads -v
> $HOME/.config/google-chrome/:/data -v /dev/snd:/dev/snd -v
> /dev/shm:/dev/shm --name chrome --security-opt
> seccomp=/home/user/Documents/Chrome/Jess1/a.json jess/chrome google-chrome
> --user-data-dir
>
> I get the same result if I run --security-opt seccomp=unconfined
>
> 3) a.jason (is one provided by mosajjal -- also tried ones found on
> https://github.com/docker/docker/blob/master/profiles/seccomp/default.json
> and Jess' at
> https://github.com/jfrazelle/dotfiles/blob/master/etc/docker/seccomp/chrome.json
> with the same outcome.
>
> 4) Docker Inspect (have added as attachment)
> DockerInspect.txt
> <https://github.com/jfrazelle/dockerfiles/files/341881/DockerInspect.txt>
>
> 5) Systemctl status docker (errors may mean something, but I think they
> are because I wasn't using --rm)
>
> systemctl status docker
> ? docker.service - Docker Application Container Engine
> Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor
> preset: enabled)
> Active: active (running) since Thu 2016-06-30 08:33:21 EDT; 3h 37min ago
> Docs: https://docs.docker.com
> Main PID: 770 (docker)
> Tasks: 20
> Memory: 61.9M
> CPU: 1min 23.649s
> CGroup: /system.slice/docker.service
> +-770 /usr/bin/docker daemon -H fd:// --userns-remap default
> +-864 docker-containerd -l
> /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc
> --start-timeout 2m
>
> Jun 30 11:53:39 debian docker[770]: time="2016-06-30T11:53:39-04:00"
> level=error msg="containerd: start container" error="oci runtime error:
> could not synchroni
> Jun 30 11:53:40 debian docker[770]:
> time="2016-06-30T11:53:40.020387411-04:00" level=error msg="Handler for
> POST /v1.23/containers/7df7a3e8ac6e7d275a56a442c8f13
> Jun 30 11:54:31 debian docker[770]:
> time="2016-06-30T11:54:31.514335968-04:00" level=error msg="Handler for
> POST /v1.23/containers/create returned error: Confli
> Jun 30 11:54:37 debian docker[770]: time="2016-06-30T11:54:37-04:00"
> level=error msg="containerd: start container" error="oci runtime error:
> could not synchroni
> Jun 30 11:54:37 debian docker[770]:
> time="2016-06-30T11:54:37.988198554-04:00" level=error msg="Handler for
> POST /v1.23/containers/399eab5c18c1e30d7e0b021cb1a6d
> Jun 30 12:05:40 debian docker[770]:
> time="2016-06-30T12:05:40.046395366-04:00" level=error msg="Handler for
> POST /v1.23/containers/create returned error: Confli
> Jun 30 12:05:58 debian docker[770]:
> time="2016-06-30T12:05:58.819988891-04:00" level=error msg="Handler for GET
> /v1.23/containers/chrome/json returned error: No
> Jun 30 12:05:58 debian docker[770]:
> time="2016-06-30T12:05:58.820769533-04:00" level=error msg="Handler for GET
> /v1.23/images/chrome/json returned error: No suc
> Jun 30 12:06:06 debian docker[770]: time="2016-06-30T12:06:06-04:00"
> level=error msg="containerd: start container" error="oci runtime error:
> could not synchroni
> Jun 30 12:06:06 debian docker[770]:
> time="2016-06-30T12:06:06.732255705-04:00" level=error msg="Handler for
> POST /v1.23/containers/f05e6b18b8c6322582e43eb76dece
> lines 1-22/22 (END)
>
> 6) Steps used to add --userns-remap to daemon
> cp /lib/systemd/system/docker.service /etc/systemd/system/
> nano /etc/systemd/system/docker.service
> Change:
>
> ExecStart=/usr/bin/docker daemon --userns-remap=default -H fd://
> systemctl daemon-reload
> systemctl restart docker
>
> 7) I believe my swap is functioning (gparted shows swap partition and) by:
> cat /proc/meminfo
> MemTotal: 1278664 kB
> MemFree: 82872 kB
> MemAvailable: 579576 kB
> Buffers: 71696 kB
> Cached: 535700 kB
> SwapCached: 42396 kB
> Active: 533680 kB
> Inactive: 551536 kB
> Active(anon): 218592 kB
> Inactive(anon): 263712 kB
> Active(file): 315088 kB
> Inactive(file): 287824 kB
> Unevictable: 32 kB
> Mlocked: 32 kB
> SwapTotal: 1307644 kB
> SwapFree: 1066908 kB
> Dirty: 32 kB
> Writeback: 0 kB
> AnonPages: 462984 kB
> Mapped: 106760 kB
> Shmem: 4612 kB
> Slab: 65992 kB
> SReclaimable: 45060 kB
> SUnreclaim: 20932 kB
> KernelStack: 4992 kB
> PageTables: 17888 kB
> NFS_Unstable: 0 kB
> Bounce: 0 kB
> WritebackTmp: 0 kB
> CommitLimit: 1946976 kB
> Committed_AS: 2691100 kB
> VmallocTotal: 34359738367 kB
> VmallocUsed: 0 kB
> VmallocChunk: 0 kB
> HardwareCorrupted: 0 kB
> AnonHugePages: 0 kB
> HugePages_Total: 0
> HugePages_Free: 0
> HugePages_Rsvd: 0
> HugePages_Surp: 0
> Hugepagesize: 2048 kB
> DirectMap4k: 71616 kB
> DirectMap2M: 1239040 kB
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/156#issuecomment-229717277>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbPrmnnl2RyGPVg08LEENR8G63rjMks5qQ_KigaJpZM4JARl->
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
Thanks Jess...any chance you have blog post url?  I'll try to google it...

**Comment by jfrazelle** [comment]
Sorry on a plane on my phone

On Thursday, June 30, 2016, senrabdet <notifications@github.com> wrote:

> Thanks Jess...any chance you have blog post url? I'll try to google it...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/156#issuecomment-229719030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbAQDoV7wrKcmazZuX4_-v61Ex3Elks5qQ_QMgaJpZM4JARl->
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
https://blog.jessfraz.com/post/runc-containers-on-the-desktop/

On Thursday, June 30, 2016, Jessica Frazelle <me@jessfraz.com> wrote:

> Sorry on a plane on my phone
>
> On Thursday, June 30, 2016, senrabdet <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Thanks Jess...any chance you have blog post url? I'll try to google it...
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/156#issuecomment-229719030>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABYNbAQDoV7wrKcmazZuX4_-v61Ex3Elks5qQ_QMgaJpZM4JARl->
>> .
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
Cool...safe flight!  Have seen post but haven't dug into it yet.  Will get started...:)

**Comment by senrabdet** [comment]
Hi All:

Have taken a temporary break from trying "runc" (will pick that up again) and at the moment am trying Docker Run as have been told runc will only let me run in containers as root (is that correct?  My assumption is runc is where things are heading).  My overall goal eventually is to use Chrome in Docker as "non-root" and without "---cap-add SYS_ADMIN" or the no sandbox flags for security reasons.  

My data below show a running container without the sys_admin flag, though I've tried it with that flag and at least superficially get the same results:  container starts, no gui.

1) Summary
I can get my chrome containter to start (whohu) but don't get a GUI yet (again, I can get the GUI to start if I use the no sandbox flag).  The container stays up and doesn't crash:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
567fa8984ba0        jess/chrome         "google-chrome --user"   49 minutes ago      Up 49 minutes                           chrome

NOTE:  I don't think the "no gui" is a problem with not having User Name spaces in my kernel as shown by cat /boot/config-`uname -r`, where I get "CONFIG_USER_NS=y" in the output, and by the fact that the container starts without a name spaces error.

Am providing detail below - may be "oversharing" especially if I'm on the wrong track....

2)  Docker Run command
strace docker run -d         --net host         -v /etc/localtime:/etc/localtime:ro    --cap-add SYS_PTRACE  --security-opt seccomp:/home/user/Documents/Chrome/chrome.json      -v /tmp/.X11-unix:/tmp/.X11-unix         -e DISPLAY=unix$DISPLAY         -v $HOME/Downloads:/root/Downloads         -v $HOME/Pictures:/root/Pictures         -v $HOME/Torrents:/root/Torrents         -v $HOME/.chrome:/data     --device /dev/video0    -v /dev/shm:/dev/shm         -v /etc/hosts:/etc/hosts         --device /dev/snd         --device /dev/dri          --group-add audio         --group-add video   --disable-content-trust      --name chrome         jess/chrome --user-data-dir=/data --force-device-scale-factor=1         --proxy-server="$proxy" --host-resolver-rules="$map" "$args" 

3)  Docker file
NOTE:  per attached strace results further down, I am getting various what I take to be "can't find lib file" errors like "open("/opt/google/chrome/libavahi-client.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)".  I tried adding in libraries in my Docker file, and the errors seem to persist. I may be adding the wrong ones or possibly even after adding them some permissions error to the "/opt/google/chrome" container is stopping them from being started/accessed?  Or missing libs may not be the problem?

``
FROM debian:sid
MAINTAINER Jessica Frazelle <jess@docker.com>

RUN apt-get update && apt-get install -y strace

#Test - see if adding libraries matters
RUN apt-get install libcomerr2 libdatrie-dev libdbus-glib-1-2 libgcrypt11-dev libgmp-dev libgpg-error-dev libgraphite2-3 libharfbuzz-dev libnettle6 libidn11 libk5crypto3 libkeyutils-dev libkrb5-3 libkrb5support0 liblzma-dev nettle-dev libp11-kit-dev libresolv-wrapper libselinux1-dev libsystemd-dev libtasn1-6 libxau6 libxdmcp-dev libxinerama-dev libavahi-client-dev libdbus-glib-1-dev -y

ADD https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb /src/google-talkplugin_current_amd64.deb

RUN echo 'deb http://httpredir.debian.org/debian testing main' >> /etc/apt/sources.list && \
	apt-get update && apt-get install -y \
	ca-certificates \
	curl \
	hicolor-icon-theme \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libv4l-0 \
	-t testing \
	fonts-symbola \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	--no-install-recommends \
	&& dpkg -i '/src/google-talkplugin_current_amd64.deb' \
	&& apt-get purge --auto-remove -y curl \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /src/*.deb

COPY local.conf /etc/fonts/local.conf

#ENTRYPOINT [ "strace", "-ff", "google-chrome" ]
ENTRYPOINT [ "google-chrome" ]
CMD [ "--user-data-dir=/data" ]


NOTE:  can't get the following other data/results to paste into post, so am attaching them...

4)  .json
I've tried various .json files from Jess and others that as best I can tell only change whether I can run strace or not.  Have attached the one I'm using for these results.

[chromejson.txt](https://github.com/jfrazelle/dockerfiles/files/355592/chromejson.txt)

5)  Strace from outside of the container.
NOTE:  various "No such file or directory" errors - assume these matter?

[HostStrace.txt](https://github.com/jfrazelle/dockerfiles/files/355593/HostStrace.txt)


6)  Strace from inside the container once it's up (docker exec chrome strace google-chrome)
NOTE:  more "No such file or directory" errors, including ones that at first blush seem to be for libs I've tried to add
[ContainerStrace.txt](https://github.com/jfrazelle/dockerfiles/files/355594/ContainerStrace.txt)


7)  Docker inspect results
[DockerInspect.txt](https://github.com/jfrazelle/dockerfiles/files/355595/DockerInspect.txt)

**Comment by senrabdet** [comment]
Is  the uidmapping in Jess' .json is machine specific?  I've tried different ones, testing them in "runc create containerid" and even if I use my host user id no joy.  Where does "886432" come from?
 
"linux": {
        "uidMappings": [
            {
                "hostID": 886432,
                "containerID": 0,
                "size": 46578392
            }
        ],

**Comment by jessfraz** [comment]
clsoing as same as https://github.com/jessfraz/dockerfiles/issues/65#issuecomment-266515801
