### ISSUE TITLE
buttslock - nothing happens

### ISSUE THREAD

**Issue by Rohlik** [jessfraz/dockerfiles#158]
Hello,
I have problem with your Dockerfile - buttslock.
I run container with `docker run -d -ti -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /var/run/dbus:/var/run/dbus -v /tmp/.X11-unix:/tmp/.X11-unix --name locker -e DISPLAY=unix$DISPLAY -e USER=tro buttslock`
and when my laptop go to sleep mode or lock mode nothing happens.
Using Debian 8.2.
Thx for help.

**Comment by jessfraz** [comment]
this should be fixed or working but let me know if otherwise
