### ISSUE TITLE
Docker (desktop) apps perplexities

### ISSUE THREAD

**Issue by brunetto** [jessfraz/dockerfiles#16]
Hi Jess!!
First of all, thanks for shared your dockerized desktop apps!! And nice [post](https://blog.jessfraz.com/posts/docker-containers-on-the-desktop.html)!!

Then, I have some thoughts about running desktop apps in docker (even if I really like the idea and find it extremely useful).

First, the size: a chrome binary is ~100 MB while your chrome docker image is ~700MB. But I can deal with it if I only need to dockerize few apps.

The second issue, that is about docker itself, is the fact it runs as root. I understand it is necessary to have the docker daemon running as root, but having the containers too as root can be a problem. You need to be able to be root (or sudoer) to run and kill the dockerized apps. Another example is that if I download something from your dockerized chrome I am not able to open it. Chrome responds 

```
Please start Google Chrome as a normal user. To run as root, you must specify an alternate --user-data-dir for storage of profile information.
```

Am I missing something?

**Comment by brunetto** [comment]
Ah, and it shut you out from your chrome profile on the chrome installed on your systems changing the owner of the folders to root.

**Comment by jfrazelle** [comment]
Don't mount the volume with the chrome profile, and you can run with -u to
specify a user

On Sunday, April 26, 2015, brunetto <notifications@github.com> wrote:

> Ah, and it shut you out from your chrome profile on the chrome installed
> on your systems changing the owner of the folders to root.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/16#issuecomment-96366546>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Also I'm not forcing you to use my dockerfiles, if you take offense / don't
like them it is more than simple to create your own, mine are not the only
option you have.

On Sunday, April 26, 2015, Jessica Frazelle <me@jessfraz.com> wrote:

> Don't mount the volume with the chrome profile, and you can run with -u to
> specify a user
>
> On Sunday, April 26, 2015, brunetto <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Ah, and it shut you out from your chrome profile on the chrome installed
>> on your systems changing the owner of the folders to root.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/16#issuecomment-96366546>
>> .
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by brunetto** [comment]
Maybe I didn't explain myself well enough... I do love our solutions... I was just asking if there were "best practices" or advises to deal with those two problems (especially the root one).
Moreover, given that, if I'm not wrong, you work at Docker, maybe your opinion could be interesting and helpful.

**Comment by jfrazelle** [comment]
Hmm yeah so I starting changing a bunch of these to not be root like spotify etc so it's a wip you can also use the -u flag look at the notify-osd container that one I pass my current user too because it needs the dbus session, basically all are super hacky tho

**Comment by pwFoo** [comment]
I'm have some working containers change user inside the container start script with sudo and also a dockerfile / build time user solution (chromium, keepassx, atom). 
Both seems to be working fine.

**Comment by jessfraz** [comment]
closing as this is not bugs with this repo, thanks! but feel free to discuss!
