### ISSUE TITLE
Spotify - GLib-GIO-CRITICAL whie trying to play any song

### ISSUE THREAD

**Issue by wklm** [jessfraz/dockerfiles#216]
Hi, thanks for the containers you're providing! 
I have a small issue with the spotify one. 
While trying to play anything i'm getting this: 

`GLib-GIO-CRITICAL **: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed`

and the track jumps to the next one in an endless loop. 
I'm using the latest docker on centos7 if that matters. 
Any hints how can i deal with that? 

cheers,
wojtek

**Comment by Rohlik** [comment]
Same problem here. I am using actual version of Docker image with this start cmd:
```
docker run -d \
                -v /etc/localtime:/etc/localtime:ro \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                -v $HOME/.spotify/config:/home/spotify/.config/spotify \
                -v $HOME/.spotify/cache:/home/spotify/spotify \
                -e DISPLAY=unix$DISPLAY \
                -e QT_DEVICE_PIXEL_RATIO \
                --security-opt seccomp:unconfined \
                --device /dev/snd \
                --device /dev/dri \
                --group-add audio \
                --group-add video \
                --name spotify \
                jess/spotify
```

**Comment by DarkArc** [comment]
The same thing happens to me, I get the following:
```
(spotify:1): GLib-GIO-CRITICAL **: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
```

**Comment by W1lkins** [comment]
I also get this if it's of any help

```
(spotify:1): GLib-GIO-CRITICAL **: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

(spotify:1): GLib-GIO-CRITICAL **: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

**Comment by jessfraz** [comment]
I do not use pulseaudio I just alsa, so if you have pulse audio on your host that might be interferring.

**Comment by W1lkins** [comment]
I use alsa too, no pulseaudio installed :smile_cat:

I'm still googling around for a fix

**Comment by stoneavenue** [comment]
Anyone had any luck?  my terminal skills are growing by leaps and bounds trying to get this fixed 💯

**Comment by codec** [comment]
A workaround for me was switching to Spotify's testing version, not sure what's actually going on :man_shrugging:

**Comment by jessfraz** [comment]
this should be fixed or working but let me know if otherwise

**Comment by tdakanalis** [comment]
I just tried to run as root user and it works !

**Comment by sergioteixeiraptc** [comment]
works as root, not as a normal user. btw any idea how to map a bluetooth headset?

**Comment by yrizk** [comment]
running it as root is not advised, but that gave me a clue. for me, I had reinstated a backup, which reinstated the old $HOME/.config/spotify folder but under uid, which can't be read by this uid , which lead to it showing that message. if you remove that folder and reopen it, you'll get back to the login screen and then you won't get those error messages (dbus actually working is a whole other can of worms)

**Comment by ProteanCode** [comment]
That was damn stupid in my case; I had to visit "Settings -> Sound -> Applications" and turn "Spotify" to "ON" (Ubuntu 18.04).

I have no idea if I ever turned it off, or it happened itself.

**Comment by mouchimotte** [comment]
Same here, with little change in the dockerfile to fix previous error :

```
FROM debian:sid-slim
LABEL maintainer "Jessie Frazelle <jess@linux.com>"

RUN	apt-get update && apt-get install -y \
	dirmngr \
	gnupg \
	curl apt-transport-https ca-certificates \
	--no-install-recommends \
	&& curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add - \
	&& echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list \
	&& apt-get update && apt-get install -y \
	alsa-utils \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libpulse0 \
	libsm6 \
	spotify-client \
	xdg-utils \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

ENV HOME /home/spotify
RUN useradd --create-home --home-dir $HOME spotify \
	&& gpasswd -a spotify audio \
	&& chown -R spotify:spotify $HOME

WORKDIR $HOME
USER spotify

# make search bar text better
RUN echo "QLineEdit { color: #000 }" > /home/spotify/spotify-override.css

ENTRYPOINT	[ "spotify" ]
CMD [ "-stylesheet=/home/spotify/spotify-override.css" ]
```

I got the same error:

`(spotify:1): GLib-GIO-CRITICAL **: 09:57:29.219: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed`

**Comment by Jihadist** [comment]
Have the same issue with pulse but sound works

**Comment by yrizk** [comment]
Hello,

I am Yohann's brother in law. I got access to his email. If you haven't
heard the news, Yohanna died in an accident a couple of weeks ago. I'm not
sure whats relationship with him but thought you should know.
If you have any questions, please feel free to call or email me.
Bobby
831-888-7823
carrillo.robert@sbcglobal.net
