### ISSUE TITLE
`hollywood` at 80x23

### ISSUE THREAD

**Issue by cheerfulstoic** [jessfraz/dockerfiles#221]
I was so excited to see that there was a `hollywood` docker container.  But I can't seem to make it appear at a size greater than 80x23.  To connect to the container I do:

    docker exec -it hollywood bash

And then I run `hollywood`.  I've also tried `tmux attach -d`, but no luck.

I'm probably missing some `docker` and/or `tmux` knowledge here...

**Comment by jessfraz** [comment]
It should resize the first time you run it, why do you need to exec into it?

**Comment by cheerfulstoic** [comment]
Mainly because I didn't know/understand about `docker run`, `docker run` got it going, thanks!

For anybody following behind me:

```ruby
docker run -it jess/hollywood
```
