### ISSUE TITLE
Failed to move to new namespace

### ISSUE THREAD

**Issue by ZanyXDev** [jessfraz/dockerfiles#222]
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
uname -a
Linux ubn-300V3A 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by koep** [comment]
See #156
