### ISSUE TITLE
[Improvement] Slack: Consider rebasing the image on debian:stretch-slim.

### ISSUE THREAD

**Issue by mrorgues** [jessfraz/dockerfiles#267]
Please consider rebasing the image on debian:stretch-slim instead of debian:stretch.

The image generated is much lighter (about 100 MB lighter)!

Here is my Dockerfile:
https://github.com/mrorgues/dockerfiles/blob/master/slack/Dockerfile

Comparison:
mrorgues/slack     471MB
jess/slack              570MB

Thanks

**Comment by jessfraz** [comment]
Open a PR please
