### ISSUE TITLE
Skype silently exits unless run interactively and launching manually

### ISSUE THREAD

**Issue by codec** [jessfraz/dockerfiles#280]
For some reason Skype always silently exits (exit code 0 and no output at all) when using the run command from the Dockerfile (or the one from docker funcs in dotfiles).

However, if I start it with `/bin/bash` as entrypoint, then run the `skypeforlinux` binary, it works just fine.

This is the run command I use (also passing in pulseaudio from my host):
```
docker run -t -i \
	-v /etc/localtime:/etc/localtime:ro \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v $HOME/.Skype:/home/skype/.Skype \
	-v /run/user/1000/pulse:/run/user/1000/pulse \
	-e PULSE_SERVER=unix:/run/user/1000/pulse/native \
	-e "DISPLAY=unix${DISPLAY}" \
	--security-opt seccomp:unconfined \
	--device /dev/video0 \
	--group-add video \
	--group-add audio \
	--name skype \
	--entrypoint /bin/bash \
	${DOCKER_REPO_PREFIX}/skype
```

Not exactly sure what's going on or what the difference is.
I will spend some more time investigating the issue.

**Comment by orthros** [comment]
I'm having a similar issue here. 

I've done a little bit of investigation and what I think the problem might be is that `skypeforlinux` command that is being created from the `ENTRYPOINT` directive is just spawining some subprocesses and exiting immediately, which causes the container to also immediately exit.

**Comment by jessfraz** [comment]
this should be fixed now but let me know if otherwise
