### ISSUE TITLE
Creating desktop entries for containerized apps

### ISSUE THREAD

**Issue by varadgunjal** [jessfraz/dockerfiles#290]
I don't know if this is the right place to post this issue - so I'm sorry if it is irrelevant / stupid, I'll close it if so deemed. I'm trying to add launcher / desktop entries for my containerized apps (nothing against the terminal, just force of habit). For eg. I created a desktop entry for Chrome inside `/usr/share/applications/google-chrome.desktop` -

```
[Desktop Entry]
Name=Google Chrome
Type=Application
Exec=docker run --rm -it --net host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME/Downloads:/home/google-chrome/Downloads -v $HOME/.config/google-chrome/:/data --security-opt seccomp=$HOME/apps/chrome/chrome.json --device /dev/snd --name chrome jess/chrome
Terminal=false
Icon=/usr/share/icons/hicolor/64x64/apps/google-chrome.png
Name[en]=Google Chrome
```

Now I type in Google Chrome in the search bar for Applications and I see the Chrome icon. When I click on it, the command also runs. But Chrome doesn't launch. What am I missing here?

**Comment by hvanderlaan** [comment]
Hi Varadgunjal,

There could be multiple issues, for example did set the variable DISPLAY? and is ```-e DISPLAY=unix$DISPLAY``` correct ?
Please run the command on the command and if it runs past it again in the desktop entry.

Also if you use ```--net=host``` you do not need ```-v /tmp/.X11-unix:/tmp/.X11-unix```

**Comment by varadgunjal** [comment]
@hvanderlaan Thanks for the tip about --net=host. 

I had already tested the Exec command before putting it in the Desktop Entry. It works properly from the terminal. The only issue is when clicking on the icon listed in Applications.

**Comment by ahoeg** [comment]
@varadgunjal 
I tried to start a similar container with demu_run. During debugging (start dmenu_run from a terminal to get debugging output to the terminal) I found my problem. 

Start a container with **-ti** without be inside a terminal fails with `the input device is not a TTY`.

Solution should be to remove **-t** from your command. Works fine for me.

**Comment by varadgunjal** [comment]
So, you're saying that simply removing the -t flag from the Exec command should enable creation of desktop entries?

**Comment by ahoeg** [comment]
Haven't tested it to create a desktop entry, but it fixed my problem to start a graphical container from **dmenu_run** application launcher.
In my case I use docker-compose to start a service, but docker-compose itself runs inside of a container started with **-t** and the service start / docker-compose command fails with the error message 

```
the input device is not a TTY
```

So if the container start fails because of the exec command with docker run -t <...> it could work. 
Remove **-t** fixed it for me with to run apps from dmenu_run launcher...

**Comment by jessfraz** [comment]
closing as this is not bugs with this repo, thanks! but feel free to discuss!
