### ISSUE TITLE
useless dependency ?

### ISSUE THREAD

**Issue by smaftoul** [jessfraz/dockerfiles#308]
https://github.com/jessfraz/dockerfiles/blob/23816093978c5d3e73fed10acc51a4d6303ac5c4/bcc-tools/Dockerfile#L27

The package bcc is a 16 bit c compiler, which I think has nothing to do with iovisor / bcc, am I wrong ?

**Comment by jessfraz** [comment]
lol maybe, want to PR it?

**Comment by smaftoul** [comment]
Here is it : #349 

Thanks !
