### ISSUE TITLE
Inkscape Dockerfile refers to 'infoslack' instead of 'jess'

### ISSUE THREAD

**Issue by CodeLenny** [jessfraz/dockerfiles#321]
The `inkscape` image refers to `infoslack/inkscape` in the instructions.  I couldn't find that image on the Docker hub, but I could find [`jess/inkscape`](https://hub.docker.com/r/jess/inkscape/), which seems to be originating from the repo (e.g. it's being built with the rest of the docker files as the "last pushed" time matches `jess/chrome`).

Should the instructions in the Docker refer to `jess/inkscape` instead?  Link below:

https://github.com/jessfraz/dockerfiles/blob/c9fefef1b11bc45d6f471896b0d4708de5e5fa97/inkscape/Dockerfile#L6

@infoslack might you have any thoughts?

**Comment by infoslack** [comment]
I agree with you =P

**Comment by jessfraz** [comment]
please make a PR :)
