### ISSUE TITLE
missing dependencies for chrome

### ISSUE THREAD

**Issue by krystan** [jessfraz/dockerfiles#327]
Hi,

Having seen your docker-ised desktop I thought I'd take a look at some of your containers, and the first one I took a look at was chrome. All went fine although it looks like you are missing a dependency, which is present in your chromium image.

libcanberra-gtk-module 

I found without installing this I got errors.

I wondered if this was the case for everyone, after I included it and tweaked my run scripts it all works :)

**Comment by santhoshmaereddy** [comment]
Hello Krystan,

I have used the docker file from the repo "https://github.com/krystan/dockerfiles/blob/b42f955942959f7f39d3c49f86fadd6430b52cea/chrome/stable/Dockerfile" to build an image and then tried to run it which in turn resulted in below error, do you know what could be wrong ?

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted 

Environment: Windows 10 Pro
Docker Version: 17.03.1-ce

**Comment by krystan** [comment]
I need more information, please show me your run statement, I have not
attempted to run this image on windows 10 either only linux.

**Comment by jessfraz** [comment]
this is fixed now
