### ISSUE TITLE
Sound - Mac laptop

### ISSUE THREAD

**Issue by mikev1963** [jessfraz/dockerfiles#332]
How do I get sound from my docker container on a Mac laptop?  /dev/snd does not work?

Any help would be appreciated.

Thanks

**Comment by zipzit** [comment]
I see the comment in the[ blog entry:](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/) that says "The commands listed below are run on a linux machine. But Mac users, I have a special surprise for you. You can also do fun hacks with X11. Details are described [here](https://github.com/docker/docker/issues/8710)."

But the majority of the content in that issues link discusses using X11 with XQuartz interface.. lots of discussion there on making graphics stuff work, nothing at all on getting sound / Alsa / PulseAudio to work.  In fact there is a posting there: 

> xavriley commented on Jun 9, 2015
>  I'm working on sound support at the moment but it's actually quite tough. The Dockerfile that builds the boot2docker iso file actually removes the sound drivers so it won't happen without a pull request or some serious hacking.

I would love to be able to use docker for audio work.. sigh.

**Comment by jessfraz** [comment]
/dev/snd does not exist on a mac... its got to work with the vm, this issue is not in scope
