### ISSUE TITLE
Microsoft Teams dockerfile

### ISSUE THREAD

**Issue by leothelocust** [jessfraz/dockerfiles#339]
I know its gross but my company uses Microsoft Teams and its web client is woefully lacking.  They have no plans at the moment to release a Linux version.

Is it even possible to wrap a mono instance of the app or something to make it runnable on Linux?

Sorry for the noob question.
-Levi

**Comment by jessfraz** [comment]
you can use the chrome dockerfile :) and it's def not a noob question, doing anything with wine would be worse than using chrome
