### ISSUE TITLE
stable-chrome Dockerfile would not build

### ISSUE THREAD

**Issue by ebenyukhis** [jessfraz/dockerfiles#347]
Missing dependencies.  Can you take a look please?

Thank you,

Ed-

**Comment by jessfraz** [comment]
also i have jenkins setup and it alerts me for all errors in build and there have been none, i can not diagnose this without more details than "it doesnt work"

**Comment by edbenyukhis** [comment]
I will re-try and collect logs.

Thanks,

Ed-
