### ISSUE TITLE
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

### ISSUE THREAD

**Issue by dalepres** [jessfraz/dockerfiles#350]
I get the error below running jess/chrome.  I get that running it with Jess' suggested command line and I get it if I remove all unneeded options.

Error: 

> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

**Comment by jessfraz** [comment]
please see https://github.com/jessfraz/dockerfiles/issues/65

**Comment by jessfraz** [comment]
The problem is user namespaces is not enabled in your kernel.

**Comment by jessfraz** [comment]
here is the most helpful comment https://github.com/jessfraz/dockerfiles/issues/65#issuecomment-266532289

**Comment by sjortiz** [comment]
as of now you can run the container with `--privileged` you won't have the issue stated on the title.

**Comment by MicheleNicosia** [comment]
Hi all,
 it is unclear to me HOW to run an image which it is perfectly workign with docker --privileged using instead the kubernetes yaml.
I'm struggling to understand and the best i did was the following yaml, which is now giving me the same error as subject:


apiVersion: v1
kind: Pod
metadata:
 name: geneticool
spec:
  privileged: true
  allowPrivilegeEscalation: true
spec:
 #replicas: 2
 #selector:
 # matchLabels:
 # app: chrome
 containers:
   - name: render
     image: geneticool/renderer:chrome
     env:
     - name: RENDERFARM_URL
       value: "https://geneticool.com/"
 imagePullSecrets:
   - name: somesecret

Giving that, the error i see is the following:

02/07/2019 10:23:10 Autoprobing TCP port
02/07/2019 10:23:10 Autoprobing selected TCP port 5900
02/07/2019 10:23:10 Autoprobing TCP6 port
02/07/2019 10:23:10 Autoprobing selected TCP6 port 5900

02/07/2019 10:23:10 The X server says there are 10 mouse buttons.
02/07/2019 10:23:10 screen setup finished.
02/07/2019 10:23:10

The VNC desktop is:      geneticool:0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

Any idea what to change on my yaml?

I wanted to easily scale up the containers with a simple command on k8s.

Thank you.
Michele

**Comment by takahser** [comment]
According to the [docs](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities), the `--priviledged` flag will give "extended privileges to this container". This includes "nearly all the same access to the host as processes running outside containers on the host". 

I don't want my container to have these rights. Is there any other way, such as restricting the access using the `--device` flag?

> It (the `--device` flag) allows you to specify one or more devices that will be accessible within the container.

**Comment by Zeroman** [comment]
you can add
            --cap-add=SYS_ADMIN \
            --device /dev/snd \
            --device /dev/dri \
replace --priviledged
[https://awesomeopensource.com/project/yukinying/chrome-headless-browser-docker](see here)

**Comment by JunjiUmeno** [comment]
What about rootless?

**Comment by Exadra37** [comment]
Using `--cap-add=SYS_ADMIN` is almost the same as giving ROOT access to the host. DON'T DO IT.

https://www.redhat.com/en/blog/container-tidbits-adding-capabilities-container

> Bottom line: giving a process SYS_ADMIN capability is pretty close to removing all isolation. As a rule, you shouldn't do this, but it's helpful to know that you can if you need to for some reason.

**Comment by unitythemaker** [comment]
Solution for the ones who don't want to add caps to the container:
[google-chrome Failed to move to new namespace](https://stackoverflow.com/questions/59087200/google-chrome-failed-to-move-to-new-namespace)

```js
const browser = await puppeteer.launch({
  "args": [
    "--no-sandbox"
  ]
});
```

I think this should be marked as the new solution if it works for everyone.

**Comment by dhasial** [comment]
> Solution for the ones who don't want to add caps to the container: [google-chrome Failed to move to new namespace](https://stackoverflow.com/questions/59087200/google-chrome-failed-to-move-to-new-namespace)
> 
> ```js
> const browser = await puppeteer.launch({
>   "args": [
>     "--no-sandbox"
>   ]
> });
> ```
> 
> I think this should be marked as the new solution if it works for everyone.

Allowing the program to run without a profile is not a real solution
