### ISSUE TITLE
Execute a tool in a container from the host OS's terminal

### ISSUE THREAD

**Issue by Medalibi** [jessfraz/dockerfiles#354]
Hi, this probably not the place place to ask this question but any help is appreciated.

I am investigating the possibility to execute a tool installed on a container from the host OS's Terminal. As if the binary is symlinked to the OS's PATH.

I am not talking about "ssh -t" to run the command via SSH and get its output. I am more talking mounting volumes and and making it more seamless. This is for a training environment, and I am trying to make the task as easy as possible.

Thanks,
Mo

**Comment by hoshsadiq** [comment]
```shell
$ alias mytool="docker run -rm mycontainer mytool"
$ mytool myargs
```

**Comment by cristim** [comment]
I've actually been working on something like this together with @elias5k, we actually built a container image that had pre-installed and largely configured a number of development tools we use within our team.

We used docker-compose with multiple volumes mounted from the home directory and a few scripts and configs that expose the tools to the host shell. Maybe we can open source this sometime.

**Comment by Medalibi** [comment]
@hoshsadiq thanks, I guess I can alias most the binaries to be executed that way.

@cristim Yeaah, please do share. I am kinda of working on a similar solution, where I need to install some home-brew tools that require a number of libraries and some configuration that is easy for SysAdmin to do, but not so much for a non-technical person. The idea is to help the trainees use those tools easily without the need to understand Docker.
