### ISSUE TITLE
telnet no longer working

### ISSUE THREAD

**Issue by docbuc** [jessfraz/dockerfiles#388]
As `telnet` was removed from alpine:3.7 (see https://github.com/gliderlabs/docker-alpine/issues/397) `jess/telnet` is not working any more:

```
docker run -it --rm jess/telnet
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"telnet\": executable file not found in $PATH": unknown.
```

Well, I guess not so many people are using telnet these days any more...

**Comment by koep** [comment]
Thanks for reporting this @docbuc

**Comment by jessfraz** [comment]
thanks!!
