### ISSUE TITLE
Issue with remmina

### ISSUE THREAD

**Issue by MarkGaze** [jessfraz/dockerfiles#395]
When I run the `remmina` container (I'm using Elementary OS v0.4 as the host) I get the following error:

```shell
No protocol specified
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory

(remmina:1): Gtk-WARNING **: cannot open display: unix:0
```

I've successfully used the `vscode` container on the same host

**Comment by jessfraz** [comment]
please look at all the other issues with that error... seems like an X auth error: https://github.com/jessfraz/dockerfiles/issues?q=is%3Aissue+cannot+open+display%3A+unix%3A0+is%3Aclosed

**Comment by MarkGaze** [comment]
Thanks, I did have a search but that was probably the only bit of the error message I didn't, sorry! 😞

**Comment by MarkGaze** [comment]
That worked, thanks! 😄 

Another quick question, how do you usually deal with the close button not stopping the container? Using the 'Quit' button does stop the container and I can stop it manually but just wondering how you handle it?
