### ISSUE TITLE
vscode - CentOS 6 compatibility

### ISSUE THREAD

**Issue by ilosamart** [jessfraz/dockerfiles#398]
Hello! First of all thanks for the great work :1st_place_medal: 

I was looking for a way to run VSCode in my CentOS6 machine, but since it depends on glibc >= 2.15 and CentOS comes with glibc 2.12 (i think) I couldn't easily do it. :disappointed: 

In my searches I've found your Dockerfile and tried simply changing the base image do 'debian:jessie' (oldstable) and BAM! :boom:  it worked.

So, I know it could be a 'wont fix' (because it's not a proper issue) but thought of giving at least a positive feedback and a hint for future users searching for a way to run 'vscode' in CentOS6 like me :smile: 

But it would be really nice if the base image was 'debian:jessie' and we could have CentOS6 support right out of the box :)

**Comment by jessfraz** [comment]
Thanks :) I will pass this along to the vscode team :)

**Comment by jessfraz** [comment]
also closing as it's not an active problem :)
