### ISSUE TITLE
postfix doesn't in your dockhub, I create one for temporary use

### ISSUE THREAD

**Issue by wangwenpei** [jessfraz/dockerfiles#399]
hi,

thanks for share your config. I found you haven't upload your postfix image at 
https://hub.docker.com/r/jessfraz/postfix/

so I create one at https://hub.docker.com/r/wangwenpei/postfix/

I think you should know this and I really wish you can maintained it in your repo.

**Comment by koep** [comment]
Try https://r.j3ss.co/repo/postfix/tags.
