### ISSUE TITLE
wireguard install - scripts/basic/fixdep not found

### ISSUE THREAD

**Issue by timelf123** [jessfraz/dockerfiles#403]
clean ubuntu, gcc and build-essentials installed

```
➜  ~docker run --rm -it \
        --name wireguard \
        -v /lib/modules:/lib/modules \
        -v /usr/src:/usr/src:ro \
        r.j3ss.co/wireguard:install
Building the wireguard kernel module...
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable
  CC [M]  /wireguard/src/main.o
/bin/sh: scripts/basic/fixdep: not found
make[2]: *** [scripts/Makefile.build:334: /wireguard/src/main.o] Error 127
make[1]: *** [Makefile:1552: _module_/wireguard/src] Error 2
make: *** [Makefile:36: module] Error 2
```

```
➜  ~ ls /usr/src
fuse-3.0.0               linux-headers-4.13.0-31-generic  linux-headers-4.15.0-33
fuse-3.0.0.tar.gz        linux-headers-4.15.0-32          linux-headers-4.15.0-33-generic
linux-headers-4.13.0-31  linux-headers-4.15.0-32-generic  s3fs-fuse
➜  ~ uname -r
4.15.0-33-generic
```

**Comment by jhf2442** [comment]
same issue, module builds fine outside of the docker container

**Comment by Mehran** [comment]
same error .

**Comment by OJFord** [comment]
@deltasquare4 Did deltasquare4/dockerfiles@ba6b0ac fix it for you? Could you open a PR here if so? 🙂

**Comment by deltasquare4** [comment]
@OJFord Thanks for the mention. It did fix the build for me. I meant to create a PR, but completely slipped out of my mind because I went another way. Done.

**Comment by abcdef123ghi** [comment]
> clean ubuntu, gcc and build-essentials installed
> 
> ```
> ➜  ~docker run --rm -it \
>         --name wireguard \
>         -v /lib/modules:/lib/modules \
>         -v /usr/src:/usr/src:ro \
>         r.j3ss.co/wireguard:install
> Building the wireguard kernel module...
> getconf: LFS_CFLAGS: unknown variable
> getconf: LFS_LDFLAGS: unknown variable
> getconf: LFS_LIBS: unknown variable
>   CC [M]  /wireguard/src/main.o
> /bin/sh: scripts/basic/fixdep: not found
> make[2]: *** [scripts/Makefile.build:334: /wireguard/src/main.o] Error 127
> make[1]: *** [Makefile:1552: _module_/wireguard/src] Error 2
> make: *** [Makefile:36: module] Error 2
> ```
> ```
> ➜  ~ ls /usr/src
> fuse-3.0.0               linux-headers-4.13.0-31-generic  linux-headers-4.15.0-33
> fuse-3.0.0.tar.gz        linux-headers-4.15.0-32          linux-headers-4.15.0-33-generic
> linux-headers-4.13.0-31  linux-headers-4.15.0-32-generic  s3fs-fuse
> ➜  ~ uname -r
> 4.15.0-33-generic
> ```
I have same issue,how did yo resolve this problem,thank you

**Comment by koliyo** [comment]
Same problem here :/
