### ISSUE TITLE
Tor browser will not load?

### ISSUE THREAD

**Issue by matt812** [jessfraz/dockerfiles#409]
Is it just me, or is the tor browser no longer loading with this new version?

XPCOMGlueLoad error for file /usr/local/bin/Browser/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

Might I be doing something wrong?

**Comment by koep** [comment]
Probably related to https://github.com/jessfraz/dockerfiles/pull/406.
Haven't had the chance to test the PR yet.

**Comment by koep** [comment]
Fixed via #406.
