### ISSUE TITLE
cheese

### ISSUE THREAD

**Issue by gschaetz** [jessfraz/dockerfiles#411]
Run command for cheese is not supplied and webcam is not showing up.

**Comment by jessfraz** [comment]
docker run -d -v /etc/localtime:/etc/localtime:ro -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=unix${DISPLAY}" -v "${HOME}/Pictures:/root/Pictures" --device /dev/video0 --device /dev/snd --device /dev/dri --name cheese ${DOCKER_REPO_PREFIX}/cheese

from: https://github.com/jessfraz/dotfiles/blob/master/.dockerfunc#L133
