### ISSUE TITLE
Alpine container using OpenRC

### ISSUE THREAD

**Issue by danilofalcao** [jessfraz/dockerfiles#442]
Hi Jess,

I wanted to create a PR for this Alpine container using OpenRC into your dockerfiles but I don' t have permission to do it.

If you think it's a good one (https://github.com/danilofalcao/dockerfiles/tree/master/alpine) just let me know.

❤️

-dfs

**Comment by jessfraz** [comment]
ah thanks! I try to keep this repo only to dockerfiles I use to make sure I catch breaks, but thanks so much :)
