### ISSUE TITLE
powershell-azure migrate from AzureRM to Az

### ISSUE THREAD

**Issue by alexeldeib** [jessfraz/dockerfiles#445]
Love the collection of dockerfiles! Awesome work.

I tried pulling this image and importing AzureRM module but found neither it nor AzureAD was installed. I tried building the image myself and noticed some errors which failed the module install but not the image build. After reflecting for a moment, I realized I don't think AzureRM is compatible with PS 6.0/Linux (some [supporting evidence](https://github.com/Azure/azure-powershell/issues/5579)). 

The plan for Azure PowerShell as a whole is to merge the OS-specific modules into a unfied `Az` module with PS 6.0. I'd propose changing this file to install Az? I did a bit of smoke testing (log in, select a subscription, basic CRUD) with the Az module and it seems stable. 

Unfortunately, I believe AzureAD as a whole is still incompatible with Linux (see [here](https://github.com/PowerShell/PowerShell/issues/5274)).

**Comment by jessfraz** [comment]
closed by #444
