### ISSUE TITLE
Slack doesn't display desktop notifications

### ISSUE THREAD

**Issue by kshcherban** [jessfraz/dockerfiles#448]
Hello,

Thanks for sharing slack example. It fails to start on my Debian Buster so i had to slightly change Dockerfile. Seems like X11 libraries incompatibility.

Here's the error that i get when slack tries to send notification
```
(slack:1): libnotify-WARNING **: 14:23:07.528: Failed to connect to proxy
``` 

I've tried various solutions to get it working, like setting `DBUS_SESSION_BUS_ADDRESS` and mounting it to container, setting various `XDG_` variables, mounting `/run/dbus` inside container, running with `--net=host`, but no luck.

Another issue with slack, that it doesn't open links in system browser. Seems that containerized slack is not usable in real life.

**Comment by mviereck** [comment]
To display notifications on host sent within a container, you need to connect the container with DBus from host.

Have a look at: [How to connect container to DBus from host](https://github.com/mviereck/x11docker/wiki/How-to-connect-container-to-DBus-from-host)

**Comment by kshcherban** [comment]
@mviereck thx, i tried that with no results.

**Comment by mviereck** [comment]
Maybe DBus only accepts messages sent by the same user.
Try the DBus setup along with `--user $(id -u):$(id -g)` to have the same user in container as on host.

**Comment by kshcherban** [comment]
Yes, that works, but there's still an issue with url links not being opened from slack when clicking.

**Comment by mviereck** [comment]
> url links not being opened from slack 

An application in a container cannot start an application on host.
If you don't include a browser in the slack image, slack finds none.

It would be possible to transfer URLs with DBus, but I am not aware that any browser (or slack) supports that.

Though, you can just use the clipboard to transfer the URL.

**Comment by kshcherban** [comment]
Thanks for your help @mviereck 
I've created modified version of slack with DBUS and updated Debian for those who may face the same issues.
https://github.com/kshcherban/slack-in-docker
