### ISSUE TITLE
Docker images not updated since 2023-06-13

### ISSUE THREAD

**Issue by ghost** [jessfraz/dockerfiles#594]
The docker images at <https://hub.docker.com/u/jess> are not updated since 2023-06-13.

Should it be like this? Previously the images were constantly rebuilt.

**Comment by ghost** [comment]
Stopped using jess images from DockerHub.

**Comment by MrJohanssons** [comment]
> Stopped using jess images from DockerHub.

Which images do you use instead?

**Comment by ghost** [comment]
I was using the chromium image from jess, distributed by DockerHub, as a base image. Now I use a local copy of the chromium/Dockerfile from this repository to build and modify directly this copy. No docker build from Jess is therefore used.

Am 4. September 2023 16:08:54 MESZ schrieb MrJohanssons ***@***.***>:
>> Stopped using jess images from DockerHub.
>
>Which images do you use instead?
>

**Comment by MrJohanssons** [comment]
Ah, okay I was hoping you found some alternative to jessies images. I still use these images all the time. I use chrome, chromium and firefox daily.

Sadly it's now been 3 months since @jessfraz last updated these.
