### ISSUE TITLE
Issue with apps failing when run for the first time

### ISSUE THREAD

**Issue by kohlerm** [jessfraz/dockerfiles#63]
Hi Jessie,
Sorry for using the issue tracker to reach out to you. 
I was recently also playing around with running X-Win applications inside docker. 
for example
https://github.com/kohlerm/docker-darktable
and 
https://github.com/kohlerm/docker-evolution

The issue is that in both cases the application fails to start during the first run, but runs fine when started for the second time.
The same happens with https://hub.docker.com/r/jonadev95/kitematic-docker/.

I'm running docker 1.8.1 on RHEL 7.1 at the moment. 

Have you experienced this?
Greetings,
Markus

**Comment by jfrazelle** [comment]
Hmmm I have not I wonder if it is something rhel specific

On Friday, September 11, 2015, kohlerm <notifications@github.com> wrote:

> Hi Jessie,
> Sorry for using the issue tracker to reach out to you.
> I was recently also playing around with running X-Win applications inside
> docker.
> for example
> https://github.com/kohlerm/docker-darktable
> and
> https://github.com/kohlerm/docker-evolution
>
> The issue is that in both cases the application fails to start during the
> first run, but runs fine when started for the second time.
> The same happens with https://hub.docker.com/r/jonadev95/kitematic-docker/
> .
>
> I'm running docker 1.8.1 on RHEL 7.1 at the moment.
>
> Have you experienced this?
> Greetings,
> Markus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/63>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
I will try out your images this weekend sometime and see what I encounter ;)

**Comment by kohlerm** [comment]
Thanks! Note that the Dockerfile for darktable just runs it twice at the moment.

**Comment by jessfraz** [comment]
this should be fixed or working now but let me know if otherwise
but since it is not a problem with dockerfiles in this repo i am closing
