### ISSUE TITLE
Add in .Xauthority

### ISSUE THREAD

**Issue by jonasfj** [jessfraz/dockerfiles#66]
I play around with the chrome container almost got it working... Seems to have some issues with the sandboxing and it runs very unstable without the sandboxing...

Anyways, to get it working with any X11 things I had to mount in .Xauthority, the following two options did the trick for me... I suspect they are needed for all images.

``` sh
    -v ${XAUTHORITY}:/xauthority:ro # mount .Xauthority file, need for auth with Xorg
    -e XAUTHORITY='/xauthority' \ # point to .Xauthority file, so clients can find magic cookie
```

**Comment by jfrazelle** [comment]
They are not needed for all images but thanks

On Thursday, September 24, 2015, Jonas Finnemann Jensen <
notifications@github.com> wrote:

> I play around with the chrome container almost got it working... Seems to
> have some issues with the sandboxing and it runs very unstable without the
> sandboxing...
>
> Anyways, to get it working with any X11 things I had to mount in
> .Xauthority, the following two options did the trick for me... I suspect
> they are needed for all images.
>
>     -v ${XAUTHORITY}:/xauthority:ro # mount .Xauthority file, need for auth with Xorg
>     -e XAUTHORITY='/xauthority' \ # point to .Xauthority file, so clients can find magic cookie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/66>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by vikstrous** [comment]
It looks like .Xauthority is needed when using [MIT-MAGIC-COOKIE](https://en.wikipedia.org/wiki/X_Window_authorization). That page lists some alternatives, but it seems like it's the most popular method.

When I tried to run the Chrome container with the magic cookie I ran into one more problem. If you don't use `--net host` you need to use `-h $(hostname)` or Chrome won't know which cookie to use to connect to the X server.

**Comment by jfrazelle** [comment]
ya its needed for some but not all

**Comment by paddy-hack** [comment]
I also ran into the X server access issue and banged my head against a wall for a wee while.  Gave up on running GUI apps on the desktop for a month or so.  Finally came across [this SO Q&A](http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container/25280523).  I wrote a [blog post](https://paddy-hack.gitlab.io/posts/running-dockerized-gui-applications/) discussing some of the security implications.

I sure would appreciate if you could mention the X server access issue.  It may save someone like myself from a headache :wink: and a bucketful of disappointment.

**Comment by vikstrous** [comment]
It seems like we have ~3 known solutions:

1. Mount Xauthority, set the domain name and expose the regular unix socket

    ```
    docker run --rm -it -h $(hostname) -e DISPLAY=:0.0 -e XAUTHORITY=$XAUTHORITY -v /tmp/.X11-unix:/tmp/.X11-unix -v $XAUTHORITY:$XAUTHORITY jess/firefox
    ```
2. a) The SO method of making a wildcard xauthority file and doing the same as above without setting the hostname
2. b) @paddy-hack 's improved hack that does the same thing as the SO script but more robustly
3. Mount Xauthority and use the unix domain socket in the abstract namespace by using --net host

    ```
    docker run --rm -it -e DISPLAY=:0.0 -e XAUTHORITY=$XAUTHORITY -v $XAUTHORITY:$XAUTHORITY --net host jess/firefox
    ```

I think solutions 1 and 3 are the simplest, but 2 optimizes for robustness and security, which is sweet. I wish there was some place we could put these solutions where people can find them more easily, but I don't know. @paddy-hack maybe including the other two solutions in your blog post would be a good start?

**Comment by paddy-hack** [comment]
I understand how 1. works and can add that to my blog post, no problem, with a note that that breaks down as soon as you want to run more than one containerized GUI application.

I'm not sure I understand how 3. works yet, but am willing to learn :wink:.

**Comment by paddy-hack** [comment]
I just pushed [changes](https://gitlab.com/paddy-hack/paddy-hack.gitlab.io/commit/2954746f073e91b95618e72a6726c05ff04c420c) to add 1. to my [blog post](https://paddy-hack.gitlab.io/posts/running-dockerized-gui-applications/) and read up a bit on adding `--net host`.  Functionally, it doesn't look much different from 1. but in addition exposes *all* of the host's networking to the container.  I'm not sure I'd want to allow my containerized desktop applications mucking around with the host's D-Bus :wink:  There's a reason I want to containerize them in the first place!

**Comment by vikstrous** [comment]
Yeah, it's not ideal. I just wanted to make the list complete. I don't know how dbus does authentication. Abstract Unix sockets are a weird and obscure feature and I would rather them not exist at all.

On June 1, 2016 4:07:24 AM PDT, Olaf Meeuwissen <notifications@github.com> wrote:
>I just pushed
>[changes](https://gitlab.com/paddy-hack/paddy-hack.gitlab.io/commit/2954746f073e91b95618e72a6726c05ff04c420c)
>to add 1. to my [blog
>post](https://paddy-hack.gitlab.io/posts/running-dockerized-gui-applications/)
>and read up a bit on adding `--net host`.  Functionally, it doesn't
>look much different from 1. but in addition exposes *all* of the host's
>networking to the container.  I'm not sure I'd want to allow my
>containerized desktop applications mucking around with the host's D-Bus
>:wink:  There's a reason I want to containerize them in the first
>place!
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jfrazelle/dockerfiles/issues/66#issuecomment-222961487

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paddy-hack** [comment]
I just put up a [little script](https://gitlab.com/dotter/docker/blob/master/bin/docker-on-x) that works fine for me (on Debian GNU/Linux, testing).

@jfrazelle If you care to point out distribution dependent problems with my script, I'll be happy to try and fix them.

**Comment by jessfraz** [comment]
closing as this is not bugs with this repo, thanks! but feel free to discuss!
