### ISSUE TITLE
Terminal rendering problem when running weechat in a docker container

### ISSUE THREAD

**Issue by ghost** [jessfraz/dockerfiles#71]
Hi jess,

As the title said, I'm having a terminal rendering problem with weechat in a container. I already posted this and much more details about it on reddit:

https://www.reddit.com/r/linuxquestions/comments/3ppeli/terminal_rendering_problem_when_running_weechat/

I would be very grateful if you could take a quick look and let me know what you think might be the problem.

Thanks and keep up the good work! :) I have played with docker on my desktop lately and your dockerfiles have been really useful.

**Comment by jfrazelle** [comment]
what is your docker version

**Comment by BytesTuner** [comment]
1.8.3

**Comment by jfrazelle** [comment]
do you have a screenshot of the weirdness

On Thu, Oct 22, 2015 at 1:30 PM, BytesTuner <notifications@github.com>
wrote:

> 1.8.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/71#issuecomment-150347862>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by BytesTuner** [comment]
https://imgur.com/QSzHF5B

**Comment by BytesTuner** [comment]
Update:

FWIW I'm running irssi in a docker container on the same computer without this rendering problem.

I also tried to build and run a weechat container on a different machine with the same result.

**Comment by Silex** [comment]
Same problem, docker `1.10.3`.

I guess it happens because weechat does funkier stuffs thank irssi with the terminal, and docker terminal support is still a bit shaky for corner cases.

**Comment by Silex** [comment]
Found this interesting issue: https://github.com/docker/docker/issues/5379

**Comment by jessfraz** [comment]
this should be fixed or working now but let me know if otherwise
