### ISSUE TITLE
[ Skype container ] Not validating my credentials

### ISSUE THREAD

**Issue by cig0** [jessfraz/dockerfiles#81]
Hi everyone,

@jfrazelle nice done! Thanks for sharing your dockerfiles so we can learn from them.

Now, Skype refuses to validate my credentials stating that the password or username are invalid - which is weird as that very same credentials works as expected on both locally-installed Skype copies and the web interface.

I tried to log into an interactive shell to debug the issue but 'run -ti jess/skype /bin/bash' won't connect either.

I would gladly appreciate if anyone can help me point to the right direction in order to debug this issue.

B.R.

**Comment by jfrazelle** [comment]
can you exec in while the container is running

**Comment by jessfraz** [comment]
this should be fixed or working now but let me know if otherwise
